apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: monitoring-worker
  template:
    metadata:
      labels:
        app: monitoring-worker
    spec:
      containers:
      - name: monitoring-worker
        image: pdm-monitoring:v3
        imagePullPolicy: Never
        env:
        - name: PYTHONUNBUFFERED
          value: "1" 
        envFrom:
        - configMapRef:
            name: monitoring-config
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"