apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
data:
  # MQTT Settings
  MONITOR_MQTT_BROKER: "mosquitto-service"
  MONITOR_MQTT_PORT: "1883"
  MONITOR_TOPIC: "factory/predictions/#"
  
  # InfluxDB Settings 
  INFLUX_URL: "http://influxdb-service:8086"
  INFLUX_ORG: "pdm_org"
  INFLUX_BUCKET: "pdm_data"
  INFLUX_TOKEN: "my-super-secret-admin-token"