apiVersion: v1
kind: ConfigMap
metadata:
  name: factory-config
  labels:
    app: smart-factory
data:
  MQTT_BROKER_HOST: "mqtt-broker"     #Nome del service che creeremo
  MQTT_BASE_TOPIC: "factory/assembly"
  SENSOR_INTERVAL: "5"
